# Generated by Django 2.2.6 on 2019-10-13 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=4000)),
                ('content', models.TextField()),
                ('language', models.CharField(choices=[('EN', 'English'), ('BN', 'বাংলা')], default='EN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Binding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.IntegerField(default=1)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child', to='ale.Chapter')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='ale.Chapter')),
            ],
        ),
        migrations.AddConstraint(
            model_name='binding',
            constraint=models.UniqueConstraint(fields=('parent', 'child'), name='unique_parenting'),
        ),
        migrations.AddConstraint(
            model_name='binding',
            constraint=models.UniqueConstraint(fields=('parent', 'serial'), name='unique_serial'),
        ),
    ]
