# Generated by Django 2.2.6 on 2019-10-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ale', '0002_chapter_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='root',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='chapter',
            name='serial',
            field=models.IntegerField(default=1),
        ),
    ]
